# Site settings
title: Erehwon Art Foundation, Inc.
baseurl: http://toffmendoza.me/sandbox-erehwon

# Build settings
markdown: kramdown
permalink: pretty
# baseurl:

address:
 - 1 Don Francisco, Villa Beatriz
 - Old Balara, Quezon City
number: +632 384 3507
email: info@erehwonartworld.com
